{% set name = "riscv-tools" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  skip: True # [not linux64]
  # needed to avoid overlinking errors
  missing_dso_whitelist:
    - '*'
  # needed to avoid unable to find specs files errors
  detect_binary_files_with_prefix: False
  # list out areas where conda can use patchelf (ignore the sysroot)
  binary_relocation:
    - 'riscv-tools/bin/**'
    - 'riscv-tools/include/**'
    - 'riscv-tools/lib/**'
    - 'riscv-tools/libexec/**'
    - 'riscv-tools/riscv64-unknown-elf/**'
    - 'riscv-tools/riscv64-unknown-linux-gnu/**'
    - 'riscv-tools/share/**'

requirements:
  build:
    ## TODO: should bound to <13?
    ## defaults to gcc/gxx when on linux64
    ## https://docs.conda.io/projects/conda-build/en/stable/resources/compiler-tools.html
    #- {{ compiler('c') }}>=10
    #- {{ compiler('cxx') }}>=10
    - gcc>=10
    - gxx>=10
    - conda-gcc-specs

    - sysroot_linux-64 2.17 # [linux64]

    # if building riscv-toolchain from source, we need to use bison==3.4.* until we have
    # https://github.com/riscv-collab/riscv-binutils-gdb/commit/314ec7aeeb1b2e68f0d8fb9990f2335f475a6e33
    - bison==3.4.* # note: doing =3.4 doesn't work

    - make
    - autoconf
    - automake
    - texinfo
    #- pkg-config
    - patch

    # TODO: re-enable individually
    - gawk
    - git
    - dtc
    - binutils
    - python
    - flex
    - libtool
    - file

    - expat # IN HOST/RUN
    #- ncurses # IN HOST/RUN
    #- gmp # IN HOST/RUN
    #- mpfr # IN HOST/RUN
    #- mpc # IN HOST/RUN
    #- zlib # IN HOST/RUN

  host:
    - gmp
    - mpfr
    - mpc
    - expat
    - ncurses
    #- xz
    - zlib

  run:
    - expat
    - mpfr
    - ncurses
    - zlib

test:
  commands:
    - test "$($PREFIX/riscv-tools/bin/riscv64-unknown-elf-gcc -dumpversion)" = "12.2.0"
    - riscv64-unknown-elf-ld --version
    - riscv64-unknown-elf-gdb --version

about:
  home: https://github.com/ucb-bar/riscv-tools-feedstock
  summary: RISC-V toolchain for UC Berkeley projects

extra:
  recipe-maintainers:
    - abejgonzalez
